### ISSUE TITLE
Can Caliburn micro version updated to 3.0.0 to support UWP specific features

### ISSUE THREAD

**Issue by balrajOla** [dchaib/Caliburn.Micro.ReactiveUI#25] opened 2016-03-15 10:05 UTC
Caliburn micro has released 3.0.0 version supporting some new controls of UWP. Can someone please update the version of caliburn here to 3.0.0

**Comment by dchaib** [comment] 2016-03-15 21:36
Not sure ReactiveUI supports UWP yet. I thought it was supposed to happen with v7. I'll check.

**Comment by haefele** [comment] 2016-03-16 22:25
AFAIK ReactiveUI does support UWP as of version 7.
I would love updates of Caliburn.Micro and ReactiveUI for this library! :smile:

**Comment by dchaib** [comment] 2016-03-17 20:51
It turns out ["6.5 works fine with UWP"](https://twitter.com/GeoffreyHuntley/status/710269944244514816). I'll work on this and try to get it out in the coming days.

**Comment by dchaib** [comment] 2016-04-02 20:43
@balrajOla I've seen your reply on the PR, but I'd prefer keep the conversation here :-)

Can you provide a way to reproduce your issue?

**Comment by dchaib** [comment] 2018-07-29 11:11
I'm closing this issue as it has not been updated for 2 years, but feel free to reach out if you still have issues!

**Closed by dchaib** 2018-07-29 11:11 UTC
